[workspace]
members = [".", "dcs-config", "dcs-test", "dcs-tool"]
exclude = ["smithay-patch"]

[package]
name = "display-config-server"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-scanner = "0.31"
wayland-server = "0.31"
smithay = { git = "https://github.com/Smithay/smithay.git", rev = "3021f619e2ae4dab8bfb1e21f3f210923b9b6582", default-features = false, features = [
    "backend_drm",
    "backend_gbm",      # GbmDevice, GbmAllocator, EGLNativeDisplay for GBM
    "renderer_gl",      # EGLDisplay, EGLContext, GlesRenderer
    "wayland_frontend",
] }
drm = "0.14"
drm-fourcc = "2"       # DrmFourcc, DrmFormat, DrmModifier
gbm = { version = "0.18", features = ["drm-support"] }
png = "0.17"
libc = "0.2"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
